# Files
CAR_WEIGHTS_FILENAME = './model/model_car.pth'
FOOD_WEIGHTS_FILENAME = './model/model_food.pth'
SCORE_DATA_FILENAME = './data/latest.csv'

# Speed
CAR_SPEED = 0.000004

# Planning
BATCH_SIZE = 1024

# Train
CAR_ACTION_LENGTH = 3
DROPOUT_RATE = 0.2
LR = 0.0001
WEIGHT_DECAY = 1e-5
CAR_GAMMA = 0.9
CAR_MAX_EPSILON = 1
CAR_MIN_EPSILON = 0.1
CAR_MAX_ALPHA = 0.1
CAR_MIN_ALPHA = 0.0001
TRAINER_STEPS = 4

# CAR layers
CAR_INPUT_LAYER_SIZE = 2
CAR_HIDDEN_LAYER_SIZE1 = 256
CAR_HIDDEN_LAYER_SIZE2 = 256
CAR_OUTPUT_LAYER_SIZE = 3

# CAR rewards
REWARD_WIN = 100
REWARD_MOVE_LEFT = 0.4
REWARD_MOVE_RIGHT = 0.8
